# Generated by Django 4.2.20 on 2025-03-13 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_post_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pub_date']},
        ),
    ]
