# Generated by Django 4.2.20 on 2025-03-18 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_alter_user_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='about',
        ),
    ]
