# Generated by Django 4.2.20 on 2025-03-21 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_alluserspostsmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllUsersPostsModel',
        ),
    ]
