# Generated by Django 4.2.20 on 2025-03-25 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
    ]
